In [36]:
import pandas as pd
import numpy as np

In [37]:
dataset=pd.read_csv("malicious_url.csv")

In [38]:
dataset['Uppercase'] = dataset['url'].str.count(r'[A-Z]')
dataset['Lowercase'] = dataset['url'].str.count(r'[a-z]')

In [39]:
dataset.head()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase
0,0,br-icloud.com.br,phishing,16,0,13
1,1,mp3raid.com/music/krizz_kaliko.html,benign,35,0,29
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,31,0,25
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,88,0,63
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,235,63,136

In [40]:
dataset['Ratio of Ucase to Lcase'] = dataset['Uppercase'] / dataset['Lowercase']

In [41]:
dataset.head()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase
0,0,br-icloud.com.br,phishing,16,0,13,0.000000
1,1,mp3raid.com/music/krizz_kaliko.html,benign,35,0,29,0.000000
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,31,0,25,0.000000
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,88,0,63,0.000000
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,235,63,136,0.463235

In [42]:
dataset['Alpha_len'] = (dataset['url'].str.count(r'[A-Z]'))+(dataset['url'].str.count(r'[a-z]'))

In [43]:
dataset.head()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase,Alpha_len
0,0,br-icloud.com.br,phishing,16,0,13,0.000000,13
1,1,mp3raid.com/music/krizz_kaliko.html,benign,35,0,29,0.000000,29
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,31,0,25,0.000000,25
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,88,0,63,0.000000,63
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,235,63,136,0.463235,199

In [44]:
dataset.tail()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase,Alpha_len
651186,651186,xbox360.ign.com/objects/850/850402.html,phishing,39,0,21,0.000000,21
651187,651187,games.teamxbox.com/xbox-360/1860/Dead-Space/,phishing,44,2,27,0.074074,29
651188,651188,www.gamespot.com/xbox360/action/deadspace/,phishing,42,0,33,0.000000,33
651189,651189,en.wikipedia.org/wiki/Dead_Space_(video_game),phishing,45,2,34,0.058824,36
651190,651190,www.angelfire.com/goth/devilmaycrytonite/,phishing,41,0,36,0.000000,36

In [45]:
dataset['count_numbers'] = dataset['url'].str.count('\d')

In [46]:
dataset.head()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase,Alpha_len,count_numbers
0,0,br-icloud.com.br,phishing,16,0,13,0.000000,13,0
1,1,mp3raid.com/music/krizz_kaliko.html,benign,35,0,29,0.000000,29,1
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,31,0,25,0.000000,25,1
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,88,0,63,0.000000,63,7
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,235,63,136,0.463235,199,22

In [47]:
dataset.tail()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase,Alpha_len,count_numbers
651186,651186,xbox360.ign.com/objects/850/850402.html,phishing,39,0,21,0.000000,21,12
651187,651187,games.teamxbox.com/xbox-360/1860/Dead-Space/,phishing,44,2,27,0.074074,29,7
651188,651188,www.gamespot.com/xbox360/action/deadspace/,phishing,42,0,33,0.000000,33,3
651189,651189,en.wikipedia.org/wiki/Dead_Space_(video_game),phishing,45,2,34,0.058824,36,0
651190,651190,www.angelfire.com/goth/devilmaycrytonite/,phishing,41,0,36,0.000000,36,0

In [48]:
def D_C_ratio(url):
    count_numbers= sum(item.isdigit() for item in url)
    Char_len=len(url)
    r = count_numbers/Char_len
    return(r)

In [49]:
dataset['Digits_to_char_ratio'] = dataset['url'].apply(D_C_ratio)

In [50]:
dataset.head()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase,Alpha_len,count_numbers,Digits_to_char_ratio
0,0,br-icloud.com.br,phishing,16,0,13,0.000000,13,0,0.000000
1,1,mp3raid.com/music/krizz_kaliko.html,benign,35,0,29,0.000000,29,1,0.028571
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,31,0,25,0.000000,25,1,0.032258
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,88,0,63,0.000000,63,7,0.079545
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,235,63,136,0.463235,199,22,0.093617

In [51]:
def U_C_ratio(url):
    Uppercase= sum(item.isupper() for item in url)
    length=len(url)
    ratio = Uppercase/length
    return(ratio)

In [52]:
dataset['Ucase_to_char_ratio'] = dataset['url'].apply(U_C_ratio)

In [53]:
dataset.head()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase,Alpha_len,count_numbers,Digits_to_char_ratio,Ucase_to_char_ratio
0,0,br-icloud.com.br,phishing,16,0,13,0.000000,13,0,0.000000,0.000000
1,1,mp3raid.com/music/krizz_kaliko.html,benign,35,0,29,0.000000,29,1,0.028571,0.000000
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,31,0,25,0.000000,25,1,0.032258,0.000000
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,88,0,63,0.000000,63,7,0.079545,0.000000
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,235,63,136,0.463235,199,22,0.093617,0.268085

In [54]:
def L_C_ratio(url):
    Lowercase= sum(item.islower() for item in url)
    length=len(url)
    ratio = Lowercase/length
    return(ratio)

In [55]:
dataset['Lcase_to_char_ratio'] = dataset['url'].apply(L_C_ratio)

In [56]:
dataset.head()

,Unnamed: 0,url,type,url_length,Uppercase,Lowercase,Ratio of Ucase to Lcase,Alpha_len,count_numbers,Digits_to_char_ratio,Ucase_to_char_ratio,Lcase_to_char_ratio
0,0,br-icloud.com.br,phishing,16,0,13,0.000000,13,0,0.000000,0.000000,0.812500
1,1,mp3raid.com/music/krizz_kaliko.html,benign,35,0,29,0.000000,29,1,0.028571,0.000000,0.828571
2,2,bopsecrets.org/rexroth/cr/1.htm,benign,31,0,25,0.000000,25,1,0.032258,0.000000,0.806452
3,3,http://www.garage-pirenne.be/index.php?option=...,defacement,88,0,63,0.000000,63,7,0.079545,0.000000,0.715909
4,4,http://adventure-nicaragua.net/index.php?optio...,defacement,235,63,136,0.463235,199,22,0.093617,0.268085,0.578723